#!/usr/bin/env python3
"""Writes tests/python-samples.valk: CSV read and written by Python's csv module.

The samples are the expected answers for tests/crosscheck.valk. Run it again after changing it:

    python3 tests/crosscheck.py
"""

import csv
import io
import os
import random

HERE = os.path.dirname(os.path.abspath(__file__))


def py_read(text, **dialect):
    rows = list(csv.reader(io.StringIO(text, newline=""), **dialect))
    # Python gives [] for an empty line, which this package skips by default
    return [row for row in rows if row != []]


def ends_in_quotes(text, **dialect):
    # Python returns what it has when the input ends inside a quoted field, where this package
    # throws. A line added after such a text lands inside the open field instead of on a row of
    # its own, which is how the case is found.
    return py_read(text + "\nZ", **dialect) != py_read(text, **dialect) + [["Z"]]


def py_write(rows, **dialect):
    out = io.StringIO(newline="")
    writer = csv.writer(out, **dialect)
    for row in rows:
        writer.writerow(row)
    return out.getvalue()


def valk_string(text):
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "%":
            out.append("\\%")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def valk_rows(rows):
    if not rows:
        return ".{}"
    return ".{ " + ", ".join(".{ " + ", ".join(valk_string(f) for f in row) + " }" for row in rows) + " }"


# Inputs picked by hand: every rule, and the ways real files break them
HANDMADE = [
    "a,b,c\r\n1,2,3\r\n",
    "a,b\nc,d",
    "a,b\rc,d\r",
    "a,b\r\n\r\n\nc,d\n\n",
    ",\n,,\n",
    "a,b,\n",
    "a,b,",
    '"a","b"\n',
    '"a,b","c\nd","e\r\nf"\r\n',
    '"say ""hi""",x\n',
    '""""\n',
    '"",""\n',
    '""\n',
    'x,""\n',
    '"a\n\nb"\n',
    "\"\r\",\"\n\"\r\n",
    ' a , "b" \n',
    'a"b,c\n',
    'ab",c\n',
    '"ab"cd,e\n',
    '"a"b"c",d\n',
    '"a" ,b\n',
    ' "a",b\n',
    '"a"\rb\n',
    'a,"b"\r\rc\n',
    "a,\rb\n",
    "naïve,日本,😀\r\n",
    "#,#\n# x\n",
    "'a','b'\n",
    "a;b,c\n",
    "\t\ta\t,\tb\n",
    '"quoted at the end"',
    'unquoted "then" quoted,"x"\n',
    '"x"""\n',
    '"x""",y\n',
    '"x" "y",z\n',
    '"",,"",\n',
]


def fuzz_texts(rng, count):
    pieces = ["a", "b", ",", '"', '"', "\n", "\r", "\r\n", " ", "é", ";", "#"]
    texts = []
    for _ in range(count):
        texts.append("".join(rng.choice(pieces) for _ in range(rng.randint(0, 24))))
    return texts


def fuzz_rows(rng, count, blanks_at_ends):
    pieces = ["a", "b", "7", " ", "\t", ",", ";", '"', "'", "\n", "\r", "\r\n", "#", "é", "日", "x y"]
    rows = []
    while len(rows) < count:
        row = []
        for _ in range(rng.randint(1, 5)):
            field = "".join(rng.choice(pieces) for _ in range(rng.randint(0, 5)))
            if not blanks_at_ends:
                # This package also quotes a field with a space or tab at either end, and
                # Python does not, so those are left out where the bytes are compared
                field = field.strip(" \t")
            row.append(field)
        rows.append(row)
    return rows


def main():
    rng = random.Random(4180)
    out = []
    out.append("// Generated by tests/crosscheck.py from Python's csv module; do not edit.")
    out.append("")
    out.append("// Text that Python's csv.reader read, and the rows it read")
    out.append("class ReadSample {")
    out.append("    text: String")
    out.append("    rows: Array[Array[String]]")
    out.append("    // Python returns the rest of the input when a quoted field is not closed; this package throws")
    out.append("    unterminated: bool")
    out.append("}")
    out.append("")
    out.append("// Rows, and the text Python's csv.writer made of them")
    out.append("class WriteSample {")
    out.append("    rows: Array[Array[String]]")
    out.append("    text: String")
    out.append("}")
    out.append("")

    reads = HANDMADE + fuzz_texts(rng, 300)
    out.append("fn python_reads() Array[ReadSample] {")
    out.append("    return .{")
    for text in reads:
        open_quote = ends_in_quotes(text)
        rows = [] if open_quote else py_read(text)
        out.append("        ReadSample { text: %s, rows: %s, unterminated: %s }" % (
            valk_string(text), valk_rows(rows), "true" if open_quote else "false"))
    out.append("    }")
    out.append("}")
    out.append("")

    # Other dialects read the same way
    out.append("fn python_reads_semicolon() Array[ReadSample] {")
    out.append("    return .{")
    for text in HANDMADE:
        open_quote = ends_in_quotes(text, delimiter=";")
        rows = [] if open_quote else py_read(text, delimiter=";")
        out.append("        ReadSample { text: %s, rows: %s, unterminated: %s }" % (
            valk_string(text), valk_rows(rows), "true" if open_quote else "false"))
    out.append("    }")
    out.append("}")
    out.append("")

    dialects = [
        ("python_writes", {}),
        ("python_writes_semicolon_lf", {"delimiter": ";", "lineterminator": "\n"}),
        ("python_writes_quote_all", {"quoting": csv.QUOTE_ALL}),
        ("python_writes_single_quote_tab", {"delimiter": "\t", "quotechar": "'"}),
    ]
    for name, dialect in dialects:
        dialect = dict(dialect)
        dialect.setdefault("lineterminator", "\r\n")
        out.append("fn %s() Array[WriteSample] {" % name)
        out.append("    return .{")
        for _ in range(60):
            rows = fuzz_rows(rng, rng.randint(1, 4), False)
            text = py_write(rows, **dialect)
            out.append("        WriteSample { rows: %s, text: %s }" % (valk_rows(rows), valk_string(text)))
        out.append("    }")
        out.append("}")
        out.append("")

    # Fields with blanks at the ends: Python writes them bare, and they must still read back
    out.append("fn python_writes_blanks() Array[WriteSample] {")
    out.append("    return .{")
    for _ in range(60):
        rows = fuzz_rows(rng, rng.randint(1, 4), True)
        text = py_write(rows, lineterminator="\r\n")
        out.append("        WriteSample { rows: %s, text: %s }" % (valk_rows(rows), valk_string(text)))
    out.append("    }")
    out.append("}")

    with open(os.path.join(HERE, "python-samples.valk"), "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
